# Generated by Django 3.2 on 2022-05-05 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nitro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Job', models.CharField(max_length=255)),
                ('Sample', models.CharField(max_length=255)),
                ('Status', models.CharField(max_length=255)),
                ('Time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
